/// Flutter icons TelegramIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TelegramIcon
///      fonts:
///       - asset: fonts/TelegramIcon.ttf
///
///
///
library;
import 'package:flutter/widgets.dart';

class TelegramIcon {
  TelegramIcon._();

  static const _kFontFam = 'TelegramIcon';

  static const IconData telegram =
      IconData(0xe800, fontFamily: _kFontFam);
}
